version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql
    environment:
      #- MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
  redis:
    container_name: redis
    image: redis:5.0.12
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379

  phpfpm:
    networks:
      - default
      - outside
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    container_name: phpfpm
    # 定制安装扩展使用
    build: ./phpfpm
    image: custom-phpfpm:v1
    # image: php:7.4-fpm #镜像默认监听9000端口
    # ports:
    #  - 9000:9000
    volumes:
      - projects:/var/www #将项目目录挂载到www
      - sshdirs:/root/.ssh #将主机ssh目录挂载到容器 for composer install

  nginx:
    depends_on:
      - phpfpm
    links:
      - phpfpm
    container_name: nginx
    image: nginx:stable
    volumes:
      - ./nginx/conf:/mnt/nginx/conf #将总的配置目录挂载进容器, 供其他地方使用
      - ./nginx/logs:/var/log/nginx # 日志目录

      #- ./phpfpm/conf/php-fpm.sock:/var/run/php-fpm.sock #指定php-fpm sock文件 取消挂载, 使用内网9000端口通信
      - projects:/var/www #将项目目录挂载到www

      - ./nginx/conf/vhosts:/etc/nginx/conf.d #挂载项目配置目录
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf #指定nginx配置文件
    ports:
      - 9017:9017
      - 9030:9030
      - 9101:9101 #wechat-domain-travel
      #...

volumes:
  projects:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/jianxiong/maliujia/3whtml #指定项目目录
  sshdirs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/jianxiong/.ssh #指定项目目录

networks:
  # docker network create outside
  outside:
    external: true